### ISSUE TITLE
Необходимо добавить pay_method в создание хэша

### ISSUE THREAD

**Issue by Dvl-es** [payuru/ANDROID_SDK_PAYU#1]
В файле LURequestBuilder.java в строку 229 необходимо добавить что-то наподобие 
`addHashPair(stringBuilder, dataMap.get(PAY_METHOD));`

Иначе в хеш функцию не попадает параметр Pay_method и при его указании сдк ругается на невалидный хеш.

**Comment by om-sv** [comment]
Добрый день!
Спасибо большое за обращение! 
Исправлено, изменения внесены в репозиторий.
[commit #5723395](https://github.com/payuru/ANDROID_SDK_PAYU/commit/5723395933ddd7d86ca19a910997c8901c5ca363)
